name: Testes unitarios

on:
  push:
    branches:
      - main
      - testes-unitarios
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Defina a versão do Node.js compatível com seu projeto

    - name: Instalar dependências
      run: |
        npm install

    - name: Rodar testes
      run: |
        npm test --verbose

    - name: Gerar cobertura de testes
      run: |
        npm run coverage
